# Generated by Django 3.2.7 on 2022-03-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='solution',
        ),
    ]
